import { db, auth } from './firebase.js';
import { APP_CONFIG } from './config.js';
import { collection, addDoc, doc, getDoc, updateDoc, onSnapshot, query, where, orderBy, serverTimestamp, setDoc, limit } from 'https://www.gstatic.com/firebasejs/10.12.0/firebase-firestore.js';
import { signInWithEmailAndPassword, onAuthStateChanged, signOut } from 'https://www.gstatic.com/firebasejs/10.12.0/firebase-auth.js';

let map, pickupMarker, deliveryMarker, polyline;
let pickupCoords=null, deliveryCoords=null, calculatedPrice=0, calculatedDistanceKm=0;
let trackingUnsub=null, courierLocationWatch=null;
const STATUSES=[['created','Sipariş Oluşturuldu'],['paid','Ödeme Alındı / Kurye Bekliyor'],['assigned','Kurye Atandı'],['picked_up','Paket Alındı'],['on_the_way','Teslimata Çıktı'],['delivered','Teslim Edildi']];
const money=n=>new Intl.NumberFormat('tr-TR',{style:'currency',currency:'TRY'}).format(Number(n||0));
const makeCode=()=>('BPK-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,6)).toUpperCase();
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const roleCache=new Map();

window.switchTab=tab=>{document.querySelectorAll('.tab-content').forEach(e=>e.classList.add('hidden'));document.getElementById('tab-'+tab)?.classList.remove('hidden');if(tab==='create'&&map)setTimeout(()=>map.invalidateSize(),300)};

async function getAddressFromCoords(lat,lng){try{const r=await fetch(`https://nominatim.openstreetmap.org/reverse?format=jsonv2&lat=${lat}&lon=${lng}&accept-language=tr`);const d=await r.json();return d.display_name||`${lat.toFixed(5)}, ${lng.toFixed(5)}`}catch{return `${lat.toFixed(5)}, ${lng.toFixed(5)}`}}
function initFreeMap(){const el=document.getElementById('map');if(!el||typeof L==='undefined')return;map=L.map('map').setView([41.2867,36.33],12);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map);document.getElementById('resetMapBtn')?.addEventListener('click',resetMap);map.on('click',async e=>{const {lat,lng}=e.latlng;if(!pickupCoords){pickupCoords=[lat,lng];pickupMarker=L.marker(pickupCoords,{draggable:true}).addTo(map).bindPopup('Alım Noktası').openPopup();pickupMarker.on('dragend',async ev=>{const p=ev.target.getLatLng();pickupCoords=[p.lat,p.lng];document.getElementById('pickupAddressInput').value=await getAddressFromCoords(p.lat,p.lng);if(deliveryCoords)calculateRoute()});document.getElementById('pickupAddressInput').value=await getAddressFromCoords(lat,lng)}else if(!deliveryCoords){deliveryCoords=[lat,lng];deliveryMarker=L.marker(deliveryCoords,{draggable:true}).addTo(map).bindPopup('Teslimat Noktası').openPopup();deliveryMarker.on('dragend',async ev=>{const p=ev.target.getLatLng();deliveryCoords=[p.lat,p.lng];document.getElementById('deliveryAddressInput').value=await getAddressFromCoords(p.lat,p.lng);calculateRoute()});document.getElementById('deliveryAddressInput').value=await getAddressFromCoords(lat,lng);calculateRoute()}});document.getElementById('packageType')?.addEventListener('change',calculatePriceAndFee)}
function resetMap(){[pickupMarker,deliveryMarker,polyline].forEach(x=>x&&map.removeLayer(x));pickupMarker=deliveryMarker=polyline=null;pickupCoords=deliveryCoords=null;calculatedPrice=0;calculatedDistanceKm=0;['pickupAddressInput','deliveryAddressInput'].forEach(id=>document.getElementById(id).value='');document.getElementById('calculatedPrice').textContent='0 TL';document.getElementById('distanceInfo').textContent='Lütfen haritadan her iki noktayı seçin';document.getElementById('payBtn').disabled=true}
async function calculateRoute(){if(!pickupCoords||!deliveryCoords)return;try{const r=await fetch(`https://router.project-osrm.org/route/v1/driving/${pickupCoords[1]},${pickupCoords[0]};${deliveryCoords[1]},${deliveryCoords[0]}?overview=full&geometries=geojson`);const d=await r.json();if(!d.routes?.length)return;calculatedDistanceKm=Number((d.routes[0].distance/1000).toFixed(1));if(polyline)map.removeLayer(polyline);polyline=L.polyline(d.routes[0].geometry.coordinates.map(c=>[c[1],c[0]]),{color:'#34d399',weight:5}).addTo(map);map.fitBounds(polyline.getBounds());calculatePriceAndFee()}catch(e){console.error(e);alert('Rota hesaplanamadı. Lütfen tekrar deneyin.')}}
function calculatePriceAndFee(){if(calculatedDistanceKm<=0)return;const mult=parseFloat(document.getElementById('packageType')?.value||1);calculatedPrice=Math.round((50+calculatedDistanceKm*15)*mult);document.getElementById('calculatedPrice').textContent=money(calculatedPrice);document.getElementById('distanceInfo').textContent=`Sürüş Mesafesi: ~${calculatedDistanceKm} km`;document.getElementById('payBtn').disabled=false}

async function createOrder(e){e.preventDefault();if(calculatedPrice<=0)return alert('Lütfen haritadan alım ve teslimat konumlarını seçin.');const code=makeCode();const order={code,status:'created',paymentStatus:'pending',price:calculatedPrice,distanceKm:calculatedDistanceKm,sender:{name:document.getElementById('senderName').value.trim(),phone:document.getElementById('senderPhone').value.trim()},receiver:{name:document.getElementById('receiverName').value.trim(),phone:document.getElementById('receiverPhone').value.trim()},pickupAddress:{fullAddress:document.getElementById('pickupAddressInput').value,coords:pickupCoords,detail:document.getElementById('pickupDetail').value.trim()},deliveryAddress:{fullAddress:document.getElementById('deliveryAddressInput').value,coords:deliveryCoords,detail:document.getElementById('deliveryDetail').value.trim()},packageType:document.getElementById('packageType').value,note:document.getElementById('note').value.trim(),courierId:null,courierName:null,courierLocation:null,createdAt:serverTimestamp(),updatedAt:serverTimestamp()};try{await setDoc(doc(db,'orders',code),order);await setDoc(doc(db,'publicOrders',code),{code,status:'created',paymentStatus:'pending',price:calculatedPrice,courierName:null,courierLocation:null,updatedAt:serverTimestamp()});localStorage.setItem('lastOrderCode',code);if(APP_CONFIG.shopierEndpoint){const fd=new FormData();fd.append('orderId',code);fd.append('price',calculatedPrice);fd.append('buyerName',order.sender.name);fd.append('buyerPhone',order.sender.phone);fd.append('buyerEmail','');const r=await fetch(APP_CONFIG.shopierEndpoint,{method:'POST',body:fd});document.open();document.write(await r.text());document.close();return}alert(`Sipariş oluşturuldu: ${code}\nÖdeme bağlantısı henüz yapılandırılmadı. Takip ekranına yönlendiriliyorsunuz.`);location.href=`track.html?code=${encodeURIComponent(code)}`}catch(err){console.error(err);alert('Sipariş oluşturulamadı: '+err.message)}}

function renderTimeline(data){const idx=STATUSES.findIndex(x=>x[0]===data.status);document.getElementById('timeline').innerHTML=STATUSES.map((s,i)=>`<div class="step ${i<=idx?'active':''}"><b>${i+1}. ${s[1]}</b></div>`).join('')}
function loadTracking(code){if(trackingUnsub)trackingUnsub();trackingUnsub=onSnapshot(doc(db,'publicOrders',code),snap=>{if(!snap.exists()){document.getElementById('trackResultBox')?.classList.add('hidden');alert('Sipariş bulunamadı!');return}const d=snap.data();document.getElementById('trackResultBox')?.classList.remove('hidden');document.getElementById('trackCodeDisplay').textContent=code;document.getElementById('trackStatusTitle').textContent=STATUSES.find(s=>s[0]===d.status)?.[1]||'Gönderiniz İşleniyor';renderTimeline(d);if(d.courierName){document.getElementById('courierBox')?.classList.remove('hidden');document.getElementById('courierName').textContent=d.courierName}else document.getElementById('courierBox')?.classList.add('hidden');updateTrackingMap(d)});}
let trackingMap,trackingMarker;function initTrackingMap(){const el=document.getElementById('trackingMap');if(!el||typeof L==='undefined')return;trackingMap=L.map(el).setView([41.2867,36.33],12);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(trackingMap)}
function updateTrackingMap(d){if(!trackingMap||!d.courierLocation?.lat)return;const p=[d.courierLocation.lat,d.courierLocation.lng];if(!trackingMarker)trackingMarker=L.marker(p).addTo(trackingMap).bindPopup('Kurye Konumu');else trackingMarker.setLatLng(p);trackingMap.setView(p,15)}

async function getRole(uid){if(roleCache.has(uid))return roleCache.get(uid);const s=await getDoc(doc(db,'users',uid));const role=s.exists()?s.data().role:null;roleCache.set(uid,role);return role}
function subscribePublicStatus(code,status){return updateDoc(doc(db,'publicOrders',code),{status,updatedAt:serverTimestamp()})}
function startCourierLocation(code){if(courierLocationWatch||!navigator.geolocation)return;courierLocationWatch=navigator.geolocation.watchPosition(async p=>{const location={lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy,updatedAt:Date.now()};try{await updateDoc(doc(db,'orders',code),{courierLocation:location,updatedAt:serverTimestamp()});await updateDoc(doc(db,'publicOrders',code),{courierLocation:{lat:location.lat,lng:location.lng,accuracy:location.accuracy},updatedAt:serverTimestamp()})}catch(e){console.error(e)}},e=>console.warn('Konum izni:',e.message),{enableHighAccuracy:true,maximumAge:5000,timeout:15000})}
function stopCourierLocation(){if(courierLocationWatch!==null){navigator.geolocation.clearWatch(courierLocationWatch);courierLocationWatch=null}}
window.takeJob=async(id,uid,name)=>{await updateDoc(doc(db,'orders',id),{courierId:uid,courierName:name,status:'assigned',updatedAt:serverTimestamp()});await subscribePublicStatus(id,'assigned')};
window.updateJob=async(id,status)=>{await updateDoc(doc(db,'orders',id),{status,updatedAt:serverTimestamp()});await subscribePublicStatus(id,status);if(status==='on_the_way')startCourierLocation(id);if(status==='delivered')stopCourierLocation()};
window.assignJob=async(id,uid,name)=>{await updateDoc(doc(db,'orders',id),{courierId:uid,courierName:name,status:'assigned',updatedAt:serverTimestamp()});await subscribePublicStatus(id,'assigned')};

function loadCourierJobs(uid,profile){const q=query(collection(db,'orders'),where('status','in',['paid','assigned','picked_up','on_the_way']));onSnapshot(q,snap=>{let html='';snap.forEach(d=>{const o=d.data();if(o.courierId&&o.courierId!==uid)return;let action='';if(!o.courierId)action=`<button onclick="takeJob('${esc(d.id)}','${esc(uid)}','${esc(profile.name||'Kurye')}')" class="flex-1 py-2 bg-emerald-400 text-black font-bold text-xs rounded-lg">İşi Al</button>`;else if(o.courierId===uid&&o.status==='assigned')action=`<button onclick="updateJob('${esc(d.id)}','picked_up')" class="flex-1 py-2 bg-emerald-400 text-black font-bold text-xs rounded-lg">Teslim Al</button>`;else if(o.courierId===uid&&o.status==='picked_up')action=`<button onclick="updateJob('${esc(d.id)}','on_the_way')" class="flex-1 py-2 bg-emerald-400 text-black font-bold text-xs rounded-lg">Teslimata Çık</button>`;else if(o.courierId===uid&&o.status==='on_the_way')action=`<button onclick="updateJob('${esc(d.id)}','delivered')" class="flex-1 py-2 bg-emerald-400 text-black font-bold text-xs rounded-lg">Teslim Et</button>`;html+=`<div class="p-4 border border-emerald-900/40 rounded-2xl bg-[#050c08] space-y-3"><div class="flex justify-between font-bold text-emerald-400"><span>${esc(o.code)}</span><span>${money(o.price)}</span></div><p class="text-xs text-slate-300"><strong>Alım:</strong> ${esc(o.pickupAddress?.fullAddress)}</p><p class="text-xs text-slate-300"><strong>Teslimat:</strong> ${esc(o.deliveryAddress?.fullAddress)}</p><p class="text-xs text-slate-400">Durum: ${esc(STATUSES.find(s=>s[0]===o.status)?.[1]||o.status)}</p><div class="pt-1 flex gap-2">${action}<a target="_blank" href="https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(o.pickupAddress?.fullAddress||'')}" class="px-3 py-2 bg-emerald-950 border border-emerald-800 text-emerald-300 rounded-lg text-xs">Alıma Git</a></div></div>`});document.getElementById('jobsList').innerHTML=html||'<div class="p-6 text-center text-slate-500">Aktif iş yok.</div>'})}

async function loadAdminDashboard(){const usersSnap=await new Promise((resolve,reject)=>onSnapshot(query(collection(db,'users'),where('role','==','courier')),resolve,reject));const couriers=[];usersSnap.forEach(d=>couriers.push({id:d.id,...d.data()}));onSnapshot(query(collection(db,'orders'),orderBy('createdAt','desc'),limit(100)),snap=>{let html='';snap.forEach(d=>{const o=d.data();const opts=couriers.map(c=>`<option value="${esc(c.id)}" ${c.id===o.courierId?'selected':''}>${esc(c.name||c.email||c.id)}</option>`).join('');html+=`<div class="p-4 border border-emerald-900/40 rounded-2xl bg-[#050c08] space-y-3 text-xs"><div class="flex justify-between"><strong class="text-white">${esc(o.code)} · ${money(o.price)}</strong><span class="text-emerald-400">${esc(STATUSES.find(s=>s[0]===o.status)?.[1]||o.status)}</span></div><p class="text-slate-400">${esc(o.sender?.name)} → ${esc(o.receiver?.name)}</p><div class="grid grid-cols-1 sm:grid-cols-3 gap-2"><button onclick="updateJob('${esc(d.id)}','paid')" class="px-3 py-2 bg-emerald-950 border border-emerald-700 text-emerald-300 rounded-lg">Ödeme Alındı</button><select onchange="assignJob('${esc(d.id)}',this.value,this.options[this.selectedIndex].text)" class="custom-input py-2"><option value="">Kurye Ata</option>${opts}</select><a target="_blank" href="track.html?code=${encodeURIComponent(o.code)}" class="px-3 py-2 bg-slate-900 border border-slate-700 text-slate-300 rounded-lg text-center">Takibi Aç</a></div></div>`});document.getElementById('adminOrdersList').innerHTML=html||'<div class="p-8 text-center text-slate-500">Henüz sipariş yok.</div>'})}

onAuthStateChanged(auth,async user=>{const adminAuth=document.getElementById('adminAuth'),adminDash=document.getElementById('adminDashboard'),courierAuth=document.getElementById('courierAuth'),courierJobs=document.getElementById('courierJobs');if(!user){adminDash?.classList.add('hidden');courierJobs?.classList.add('hidden');adminAuth?.classList.remove('hidden');courierAuth?.classList.remove('hidden');return}const role=await getRole(user.uid);if(role==='courier'){courierAuth?.classList.add('hidden');courierJobs?.classList.remove('hidden');document.getElementById('courierLogout')?.classList.remove('hidden');loadCourierJobs(user.uid,{name:user.displayName||user.email})}else if(role==='admin'){adminAuth?.classList.add('hidden');adminDash?.classList.remove('hidden');document.getElementById('adminLogout')?.classList.remove('hidden');loadAdminDashboard()}else{await signOut(auth);alert('Bu hesap için panel yetkisi tanımlı değil.')}});
document.getElementById('courierLoginForm')?.addEventListener('submit',async e=>{e.preventDefault();try{await signInWithEmailAndPassword(auth,document.getElementById('courierEmail').value,document.getElementById('courierPassword').value)}catch(x){alert(x.message)}});
document.getElementById('adminLoginForm')?.addEventListener('submit',async e=>{e.preventDefault();try{await signInWithEmailAndPassword(auth,document.getElementById('adminEmail').value,document.getElementById('adminPassword').value)}catch(x){alert(x.message)}});
document.getElementById('courierLogout')?.addEventListener('click',()=>{stopCourierLocation();signOut(auth)});document.getElementById('adminLogout')?.addEventListener('click',()=>signOut(auth));
document.getElementById('searchTrackBtn')?.addEventListener('click',()=>{const code=document.getElementById('trackCodeInput')?.value.trim().toUpperCase();if(code)loadTracking(code)});
document.addEventListener('DOMContentLoaded',()=>{initFreeMap();initTrackingMap();const params=new URLSearchParams(location.search);const code=params.get('code')||localStorage.getItem('lastOrderCode');if(code&&document.getElementById('trackCodeInput')){document.getElementById('trackCodeInput').value=code;loadTracking(code)}document.getElementById('orderForm')?.addEventListener('submit',createOrder)});
